shared:
    image: node:6

jobs:
    job1:
        steps:
          - echo: sleep 30
        requires: [~commit, ~pr]
    job2:
        steps:
          - echo: echo bye
        requires: [~commit, ~pr]
        blockedBy: job1
