shared:
    image: node:6

jobs:
    job1:
        steps:
          - echo: echo hi
        requires: [~commit, ~pr]
    job2:
        steps:
          - echo: sleep 5
        requires: [~commit, ~pr]
    job3:
        steps:
          - echo: echo bye
        requires: job1
    job4:
        steps:
          - echo: echo bye
        requires: job2
        blockedBy: job3
